
services:
  pythonapp:
    container_name: pythonapp
    build:                         # Bulid the image 
      context: .
      dockerfile: Dockerfile       # Dockerfile for the python application
    ports:
      - 8000:5000                  # expose port 5000 of the container to port 8000 on the host
    networks:
      - flasknet
    depends_on:
      - mysql

  # mysql: MySQL database service
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: testdb
    ports:
      - 3306:3306
    networks:
      - flasknet
networks:
  flasknet:
    driver: bridge