
services:
  pythonapp:
    container_name: pythonapp
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:5000
    networks:
      - flasknet
    depends_on:
      - mysql

  # mysql:
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: testdb
    ports:
      - 3306:3306
    networks:
      - flasknet
networks:
  flasknet:
    driver: bridge